name: Build Android APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Dependencies
        run: |
          pip install flet[all]
          # في حال وجود ملف requirements.txt
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build APK
        run: |
          # إضافة --no-version-check لتجنب توقف البناء بسبب تحديثات فليت المفاجئة
          flet build apk --verbose

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Asala-App-Final
          path: build/apk/*.apk
